# Generated by Django 4.2 on 2023-06-11 14:16

import base.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('photo_de_profile', models.ImageField(blank=True, default='img/navbar_logo.png', null=True, upload_to='img/')),
                ('type_adhérent', models.CharField(choices=[('Membre fondateur', 'Membre fondateur'), ('Membre actif', 'Membre actif'), ('Membre actif jeune', 'Membre actif jeune'), ('Soutien', 'Soutien'), ("Membre d'honneur ", "Membre d'honneur ")], max_length=27)),
                ('responsabilité_adhérent', models.CharField(blank=True, choices=[('Président', 'Président'), ('Viceprésident', 'Vice président'), ('Directeur Executif', 'Directeur Executif'), ('Trésorier', 'Trésorier'), ('Trésorier adjoint ', 'Trésorier adjoint '), ('Chef Projet', 'Chef Projet'), ('Coordinateur de commission ', 'Coordinateur de commission '), ('Membre Simple ', 'Membre Simple ')], max_length=27, null=True)),
                ('genre', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('nom', models.CharField(max_length=50)),
                ('prénom', models.CharField(max_length=50)),
                ('type_document_identité', models.CharField(choices=[('CIN', "Carte d'identité"), ('CS', 'Carte de séjour')], max_length=3, null=True)),
                ('numero_document_identité', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999), base.models.validate_eight_digits])),
                ('date_émission_de_la_carte', models.DateField(blank=True, null=True)),
                ('nationalité', models.CharField(max_length=50)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('numéro_de_téléphone', models.CharField(max_length=20)),
                ('adresse_email', models.EmailField(max_length=50)),
                ('commissions', models.CharField(blank=True, choices=[('Enseignement, Sciences et Technologies', 'Enseignement, Sciences et Technologies'), ('Développement et emploi', 'Développement et emploi'), ('Santé et social', 'Santé et social'), ('Culture, tourisme et environnement', 'Culture, tourisme et environnement'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('date_adhésion', models.DateField(blank=True, null=True)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('motif_depart', models.CharField(blank=True, max_length=50, null=True)),
                ('cotisation_annuelle', models.CharField(default='non payée', max_length=50)),
                ('dernière_date_de_payement', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdherentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(max_length=10)),
                ('changes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('adherent', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BanqueTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('banque_transaction', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(max_length=10)),
                ('old_data', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, default='nothing', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CaisseTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('caisse_transaction', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(max_length=10)),
                ('old_data', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, default='nothing', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Governat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='StructureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(max_length=10)),
                ('changes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('structure', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_structure', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('BN', 'Bureau National'), ('BR', 'Bureau regional'), ('BL', 'Bureau Local'), ('PR', 'Projet')], max_length=15)),
                ('libellé', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=20)),
                ('code_postal', models.CharField(max_length=4)),
                ('numéro_de_téléphone', models.CharField(max_length=20)),
                ('adresse_email', models.EmailField(max_length=254)),
                ('date_de_création', models.DateField()),
                ('date_AG', models.DateField()),
                ('délégation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='base.delegation')),
                ('gouvernorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='base.governat')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabilite', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('code_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.structure')),
                ('numero_adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.adherent')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('libelle', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Bureau Exécutif'), (2, 'Commission'), (3, 'AG'), (4, 'Conférence'), (5, 'Activité')])),
                ('date_debut', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('date_fin', models.DateField()),
                ('heure_fin', models.TimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('initiateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.structure')),
                ('membres_invites', models.ManyToManyField(blank=True, related_name='evenements_membres_invites', to='base.adherent')),
                ('partenaires', models.ManyToManyField(blank=True, related_name='evenements_partenaires', to='base.structure')),
            ],
        ),
        migrations.AddField(
            model_name='delegation',
            name='governat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='base.governat'),
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen_de_payement', models.CharField(choices=[('Banque', 'Banque'), ('Caisse', 'Caisse')], max_length=8, null=True)),
                ('numéro_chèque_ou_recu', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('entreprise', models.CharField(max_length=50)),
                ('libellé', models.CharField(max_length=50)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justificatif', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('adhérent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.adherent')),
            ],
        ),
        migrations.CreateModel(
            name='CaisseTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('entreprise', models.CharField(max_length=50)),
                ('libellé', models.CharField(max_length=50)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_de_transaction', models.CharField(choices=[('Crédit', 'Crédit'), ('Débit', 'Débit')], max_length=6)),
                ('raison_de_transaction', models.CharField(choices=[('Don', 'Don'), ('Cotisation', 'Cotisation'), ('Soutien', 'Soutien'), ('Dépenses', 'Dépenses'), ('Profits', 'Profits')], default='raison inconnue', max_length=20)),
                ('recu_numéro', models.CharField(max_length=20)),
                ('justificatif_caisse', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('adhérent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.adherent')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.structure')),
                ('évènement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.evenement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BanqueTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('entreprise', models.CharField(max_length=50)),
                ('libellé', models.CharField(max_length=50)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_de_transaction', models.CharField(choices=[('Crédit', 'Crédit'), ('Débit', 'Débit')], max_length=6)),
                ('raison_de_transaction', models.CharField(choices=[('Don', 'Don'), ('Cotisation', 'Cotisation'), ('Soutien', 'Soutien'), ('Dépenses', 'Dépenses'), ('Profits', 'Profits')], default='raison inconnue', max_length=20)),
                ('banque', models.CharField(max_length=50)),
                ('numéro_du_chèque', models.CharField(max_length=20)),
                ('justificatif_bancaire', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('adhérent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.adherent')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.structure')),
                ('évènement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.evenement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adherent',
            name='structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adherents', to='base.structure'),
        ),
        migrations.AddField(
            model_name='adherent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adherent', to=settings.AUTH_USER_MODEL),
        ),
    ]
