# Generated by Django 4.1.7 on 2023-03-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('code_adherent', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('code_struct_adherent', models.CharField(max_length=5)),
                ('nom_adherent', models.CharField(max_length=100)),
                ('prenom_adherent', models.CharField(max_length=100)),
                ('nation_adherent', models.CharField(max_length=50)),
                ('tel_adherent', models.CharField(max_length=20)),
                ('email_adherent', models.EmailField(max_length=100)),
                ('type_adherent', models.IntegerField()),
                ('date_naissance_adherent', models.DateField()),
                ('photo_adherent', models.CharField(max_length=100)),
                ('Date_sai', models.DateField()),
                ('login_adherent', models.EmailField(max_length=100)),
                ('mdp_adherent', models.EmailField(max_length=20)),
                ('observations_adherent', models.CharField(max_length=100)),
                ('cin_adherent', models.CharField(max_length=10)),
                ('genre_adherent', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('lieu_nais_adherent', models.CharField(max_length=50)),
                ('profession_adherent', models.CharField(max_length=50)),
                ('secteur_adherent', models.CharField(max_length=50)),
                ('date_adhesion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StructureAssociation',
            fields=[
                ('code_struct', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gouv_structure', models.CharField(max_length=50)),
                ('delegstruct', models.CharField(max_length=50)),
                ('date_crea', models.DateField()),
                ('type_struct', models.CharField(max_length=50)),
                ('matricule_fiscale', models.CharField(max_length=50)),
                ('JORT_crea', models.CharField(max_length=50)),
                ('nro_cpt_ban', models.CharField(max_length=50)),
                ('code_president', models.CharField(max_length=10)),
                ('code_vice', models.CharField(max_length=10)),
                ('code_direxe', models.CharField(max_length=10)),
                ('code_tresor', models.CharField(max_length=10)),
                ('code_membre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStructure',
            fields=[
                ('id_historique_struct', models.AutoField(primary_key=True, serialize=False)),
                ('date_modif_struct', models.DateTimeField(auto_now_add=True)),
                ('struct_modifie_par', models.CharField(max_length=50)),
                ('type_modif_struct', models.CharField(max_length=50)),
                ('code_struct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.structureassociation')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueAdherent',
            fields=[
                ('id_historique_client', models.AutoField(primary_key=True, serialize=False)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.CharField(max_length=100)),
                ('type_modif', models.CharField(max_length=100)),
                ('code_adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.adherent')),
            ],
        ),
    ]
