# Generated by Django 4.2 on 2023-05-10 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('type_adherent', models.CharField(choices=[('1', 'Membre fondateur'), ('2', 'Membre actif'), ('3', 'Membre actif jeune'), ('4', 'Soutien'), ('5', 'Président'), ('6', 'Directeur Executif'), ('7', 'Tresorier'), ('8', 'Simple membre')], max_length=1)),
                ('genre', models.CharField(choices=[('M', 'M.'), ('F', 'Mme.')], max_length=1)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('numero_document_identite', models.CharField(max_length=8)),
                ('nationalite', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('commissions', models.CharField(choices=[('1', 'Enseignement, Sciences et Technologies'), ('2', 'Développement et emploi'), ('3', 'Santé et social'), ('4', 'Culture, tourisme et environnement'), ('5', 'Autre')], max_length=5)),
                ('date_adhesion', models.DateField(blank=True, null=True)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('motif_depart', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdherentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('adherent', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(max_length=10)),
                ('old_data', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, default='nothing', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Governat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='StructureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('structure', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(max_length=10)),
                ('old_data', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, default='nothing', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_structure', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('BN', 'Bureau National'), ('BR', 'Bureau regional'), ('BL', 'Bureau Local'), ('PR', 'Projet')], max_length=2)),
                ('libelle', models.CharField(max_length=20)),
                ('rue', models.CharField(max_length=20)),
                ('code_postal', models.CharField(max_length=4)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_creation', models.DateField()),
                ('date_ag', models.DateField()),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='base.delegation')),
                ('governat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='base.governat')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabilite', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('code_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.structure')),
                ('numero_adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.adherent')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('libelle', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Bureau Exécutif'), (2, 'Commission'), (3, 'AG'), (4, 'Conférence'), (5, 'Activité')])),
                ('date_debut', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('date_fin', models.DateField()),
                ('heure_fin', models.TimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('initiateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.structure')),
                ('membres_invites', models.ManyToManyField(blank=True, related_name='evenements_membres_invites', to='base.adherent')),
                ('partenaires', models.ManyToManyField(blank=True, related_name='evenements_partenaires', to='base.structure')),
            ],
        ),
        migrations.AddField(
            model_name='delegation',
            name='governat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='base.governat'),
        ),
        migrations.AddField(
            model_name='adherent',
            name='structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adherents', to='base.structure'),
        ),
        migrations.AddField(
            model_name='adherent',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
