# Generated by Django 4.2 on 2023-06-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotisation',
            name='type_de_cotisation',
        ),
        migrations.AddField(
            model_name='cotisation',
            name='moyen_de_payement',
            field=models.CharField(choices=[('Banque', 'Banque'), ('Caisse', 'Caisse')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='type_document_identité',
            field=models.CharField(choices=[('CIN', "Carte d'identité"), ('CS', 'Carte de séjour')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.CharField(choices=[('Bureau National', 'Bureau National'), ('Bureau regional', 'Bureau regional'), ('Bureau Local', 'Bureau Local'), ('Projet', 'Projet')], max_length=15),
        ),
    ]
