# Generated by Django 4.2 on 2023-06-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='photo_de_profile',
            field=models.ImageField(blank=True, default='img/navbar_logo.png', null=True, upload_to='img/'),
        ),
    ]
