# Generated by Django 4.2 on 2023-06-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetransactions',
            name='raison_de_transaction',
            field=models.CharField(choices=[('Don', 'Don'), ('Cotisation', 'Cotisation'), ('Aide financier', 'Aide financier'), ('Dépenses sur évènement ', 'Dépenses sur évènement '), ("Recette d'évènement ", "Recette d'évènement")], default='raison inconnue', max_length=23),
        ),
        migrations.AlterField(
            model_name='caissetransactions',
            name='raison_de_transaction',
            field=models.CharField(choices=[('Don', 'Don'), ('Cotisation', 'Cotisation'), ('Aide financier', 'Aide financier'), ('Dépenses sur évènement ', 'Dépenses sur évènement '), ("Recette d'évènement ", "Recette d'évènement")], default='raison inconnue', max_length=23),
        ),
    ]
