# Generated by Django 4.2 on 2023-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_cotisation_type_de_cotisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.CharField(choices=[('BN', 'Bureau National'), ('BR', 'Bureau regional'), ('BL', 'Bureau Local'), ('PR', 'Projet')], max_length=15),
        ),
    ]
