# Generated by Django 4.2 on 2023-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_adherent_photo_de_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='dernière_date_de_payement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
