# Generated by Django 4.1.7 on 2023-03-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_adherent_date_sai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiqueadherent',
            name='code_adherent',
        ),
        migrations.RemoveField(
            model_name='historiquestructure',
            name='code_struct',
        ),
        migrations.DeleteModel(
            name='Adherent',
        ),
        migrations.DeleteModel(
            name='HistoriqueAdherent',
        ),
        migrations.DeleteModel(
            name='HistoriqueStructure',
        ),
        migrations.DeleteModel(
            name='StructureAssociation',
        ),
    ]
