# Generated by Django 4.2 on 2023-05-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_banquetransactionhistory_caissetransactionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotisation_type', models.CharField(choices=[('B', 'Bank'), ('C', 'Caisse')], max_length=1)),
                ('number', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('entreprise', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=50)),
                ('debit', models.BooleanField(default=False)),
                ('credit', models.BooleanField(default=False)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justificatif', models.ImageField(blank=True, null=True, upload_to='')),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.adherent')),
            ],
        ),
    ]
