# Generated by Django 4.2 on 2023-06-18 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_adherent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetransactionhistory',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
