# Generated by Django 4.1.7 on 2023-03-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_remove_historiqueadherent_code_adherent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_adherent', models.CharField(max_length=8, unique=True)),
                ('type_adherent', models.CharField(choices=[('1', 'Membre fondateur'), ('2', 'Membre actif'), ('3', 'Membre actif jeune'), ('4', 'Soutien'), ('5', 'Membre d’honneur')], max_length=1)),
                ('genre', models.CharField(choices=[('M', 'M.'), ('F', 'Mme.')], max_length=1)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('document_identite', models.CharField(choices=[('CI', "Carte d'identité"), ('CS', 'Carte de séjour')], max_length=2)),
                ('numero_document_identite', models.CharField(max_length=8)),
                ('date_delivrance_ci', models.DateField(blank=True, null=True)),
                ('date_validite_cs', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('rue', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=15)),
                ('code_postal', models.CharField(max_length=4)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('commissions', models.CharField(choices=[('1', 'Enseignement, Sciences et Technologies'), ('2', 'Développement et emploi'), ('3', 'Santé et social'), ('4', 'Culture, tourisme et environnement'), ('5', 'Autre')], max_length=5)),
                ('derniere_cotisation_payee', models.CharField(max_length=4)),
                ('date_reglement_cotisation', models.DateField()),
                ('date_adhesion', models.DateField()),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('motif_depart', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('libelle', models.CharField(max_length=20)),
                ('rue', models.CharField(max_length=20)),
                ('cite_quartier', models.CharField(max_length=15)),
                ('ville', models.CharField(max_length=15)),
                ('code_postal', models.CharField(max_length=4)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_creation', models.DateField()),
                ('date_ag', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabilite', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('code_adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.adherent')),
                ('code_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.structure')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('libelle', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Bureau Exécutif'), (2, 'Commission'), (3, 'AG'), (4, 'Conférence'), (5, 'Activité')])),
                ('date_debut', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('date_fin', models.DateField()),
                ('heure_fin', models.TimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('initiateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.structure')),
                ('membres_invites', models.ManyToManyField(blank=True, related_name='evenements_membres_invites', to='base.adherent')),
                ('partenaires', models.ManyToManyField(blank=True, related_name='evenements_partenaires', to='base.structure')),
            ],
        ),
    ]
