# Generated by Django 4.2 on 2023-06-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_adherent_dernière_date_de_payement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='date_émission_de_la_carte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
