# Generated by Django 4.2 on 2023-06-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_structure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='responsabilité_adhérent',
            field=models.CharField(choices=[('Président', 'Président'), ('Viceprésident', 'Vice président'), ('Directeur Executif', 'Directeur Executif'), ('Trésorier', 'Trésorier'), ('Trésorier adjoint ', 'Trésorier adjoint '), ('Directeur Executif', 'Directeur Executif'), ('Chef Projet', 'Chef Projet'), ('Coordinateur de commission ', 'Coordinateur de commission ')], max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='type_adhérent',
            field=models.CharField(choices=[('Membre fondateur', 'Membre fondateur'), ('Membre actif', 'Membre actif'), ('Membre actif jeune', 'Membre actif jeune'), ('Soutien', 'Soutien'), ("Membre d'honneur ", "Membre d'honneur ")], max_length=27),
        ),
    ]
