# Generated by Django 4.2 on 2023-06-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_adherent_date_émission_de_la_carte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='rue',
            new_name='adresse',
        ),
    ]
