# Generated by Django 4.2 on 2023-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cotisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquetransactions',
            name='transaction_type',
            field=models.CharField(choices=[('don', 'Don'), ('cotisation', 'Cotisation'), ('frais', 'Frais'), ('profits', 'profits')], default='don', max_length=20),
        ),
        migrations.AddField(
            model_name='caissetransactions',
            name='transaction_type',
            field=models.CharField(choices=[('don', 'Don'), ('cotisation', 'Cotisation'), ('frais', 'Frais'), ('profits', 'profits')], default='don', max_length=20),
        ),
    ]
