# Generated by Django 4.2 on 2023-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_banquetransactions_raison_de_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='responsabilité_adhérent',
            field=models.CharField(choices=[('Président', 'Président'), ('Viceprésident', 'Vice président'), ('Directeur Executif', 'Directeur Executif'), ('Trésorier', 'Trésorier'), ('Trésorier adjoint ', 'Trésorier adjoint '), ('Chef Projet', 'Chef Projet'), ('Coordinateur de commission ', 'Coordinateur de commission ')], max_length=27, null=True),
        ),
    ]
