# Generated by Django 4.2 on 2023-06-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_rue_structure_adresse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='date_ag',
            new_name='date_AG',
        ),
    ]
