# Generated by Django 4.2 on 2023-05-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_banquetransactions_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banquetransactions',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='banquetransactions',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='caissetransactions',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='caissetransactions',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='cotisation',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='cotisation',
            name='debit',
        ),
        migrations.AddField(
            model_name='banquetransactions',
            name='transaction_raison',
            field=models.CharField(choices=[('don', 'Don'), ('cotisation', 'Cotisation'), ('frais', 'Frais'), ('profits', 'profits')], default='don', max_length=20),
        ),
        migrations.AddField(
            model_name='caissetransactions',
            name='transaction_raison',
            field=models.CharField(choices=[('don', 'Don'), ('cotisation', 'Cotisation'), ('frais', 'Frais'), ('profits', 'profits')], default='don', max_length=20),
        ),
        migrations.AlterField(
            model_name='banquetransactions',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6),
        ),
        migrations.AlterField(
            model_name='caissetransactions',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6),
        ),
    ]
