# Generated by Django 4.2 on 2023-05-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_banquetransactions_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='cotisation_annuelle',
            field=models.CharField(default='non payée', max_length=50),
        ),
    ]
