# Generated by Django 4.2 on 2023-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_adherent_responsabilité_adhérent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='responsabilité_adhérent',
            field=models.CharField(blank=True, choices=[('Président', 'Président'), ('Viceprésident', 'Vice président'), ('Directeur Executif', 'Directeur Executif'), ('Trésorier', 'Trésorier'), ('Trésorier adjoint ', 'Trésorier adjoint '), ('Chef Projet', 'Chef Projet'), ('Coordinateur de commission ', 'Coordinateur de commission '), ('Membre Simple ', 'Membre Simple ')], max_length=27, null=True),
        ),
    ]
