# Generated by Django 4.1.7 on 2023-04-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_adherent_code_alter_adherent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
