# Generated by Django 4.1.7 on 2023-04-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_adherent_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='code_stucture',
            new_name='code_structure',
        ),
    ]
