# Generated by Django 4.2 on 2023-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_adherent_responsabilité_adhérent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetransactions',
            name='raison_de_transaction',
            field=models.CharField(choices=[('Don', 'Don'), ('Cotisation', 'Cotisation'), ('Soutien', 'Soutien'), ('Dépenses', 'Dépenses'), ('Profits', 'Profits')], default='raison inconnue', max_length=20),
        ),
        migrations.AlterField(
            model_name='caissetransactions',
            name='raison_de_transaction',
            field=models.CharField(choices=[('Don', 'Don'), ('Cotisation', 'Cotisation'), ('Soutien', 'Soutien'), ('Dépenses', 'Dépenses'), ('Profits', 'Profits')], default='raison inconnue', max_length=20),
        ),
    ]
