# Generated by Django 4.1.7 on 2023-04-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_code_stucture_structure_code_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='structure',
            name='type',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('governat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.governat')),
            ],
        ),
    ]
