# Generated by Django 4.1.7 on 2023-04-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_governat_structure_type_delegation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delegation',
        ),
        migrations.DeleteModel(
            name='Governat',
        ),
    ]
