# Generated by Django 4.2 on 2023-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_adherent_commissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='type_document_identite',
            field=models.CharField(choices=[('CI', "Carte d'identité"), ('CS', 'Carte de séjour')], max_length=2, null=True),
        ),
    ]
