# Generated by Django 4.1.7 on 2023-04-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_governat_remove_structure_cite_quartier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='governat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='base.governat'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='delegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='base.delegation'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='governat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='base.governat'),
        ),
    ]
