# Generated by Django 4.2 on 2023-05-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_adherent_commissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='commissions',
            field=models.CharField(blank=True, choices=[('enseignement, sciences et technologies', 'Enseignement, Sciences et Technologies'), ('développement et emploi', 'Développement et emploi'), ('santé et social', 'Santé et social'), ('culture, tourisme et environnement', 'Culture, tourisme et environnement'), ('autre', 'Autre')], max_length=200, null=True),
        ),
    ]
