# Generated by Django 4.2 on 2023-05-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_adherent_commissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='commissions',
            field=models.CharField(choices=[('1', 'Enseignement, Sciences et Technologies'), ('2', 'Développement et emploi'), ('3', 'Santé et social'), ('4', 'Culture, tourisme et environnement'), ('5', 'Autre')], default='autre', max_length=5),
        ),
    ]
