# Generated by Django 4.1.7 on 2023-04-10 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_delegation_governat_alter_structure_delegation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adherents', to='base.structure'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.CharField(choices=[('BN', 'Bureau National'), ('BR', 'Bureau regional'), ('BL', 'Bureau Local'), ('PR', 'Projet')], max_length=2),
        ),
    ]
