# Generated by Django 4.2 on 2023-04-20 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_adherenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAdherent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('type_adherent', models.CharField(choices=[('1', 'Membre fondateur'), ('2', 'Membre actif'), ('3', 'Membre actif jeune'), ('4', 'Soutien'), ('5', 'Membre d’honneur')], max_length=1)),
                ('genre', models.CharField(choices=[('M', 'M.'), ('F', 'Mme.')], max_length=1)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('document_identite', models.CharField(choices=[('CI', "Carte d'identité"), ('CS', 'Carte de séjour')], max_length=2)),
                ('numero_document_identite', models.CharField(max_length=8)),
                ('date_delivrance_ci', models.DateField(blank=True, null=True)),
                ('date_validite_cs', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('rue', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=15)),
                ('code_postal', models.CharField(max_length=4)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('commissions', models.CharField(choices=[('1', 'Enseignement, Sciences et Technologies'), ('2', 'Développement et emploi'), ('3', 'Santé et social'), ('4', 'Culture, tourisme et environnement'), ('5', 'Autre')], max_length=5)),
                ('derniere_cotisation_payee', models.CharField(max_length=4)),
                ('date_reglement_cotisation', models.DateField()),
                ('date_adhesion', models.DateField()),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('motif_depart', models.CharField(blank=True, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.structure')),
            ],
            options={
                'verbose_name': 'historical adherent',
                'verbose_name_plural': 'historical adherents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
