# Generated by Django 4.2 on 2023-05-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_adherent_type_adherent'),
        ('base', '0014_alter_adherent_commissions'),
    ]

    operations = [
    ]
