# Generated by Django 4.2 on 2023-05-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_merge_20230525_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adherenthistory',
            old_name='old_data',
            new_name='changes',
        ),
        migrations.RemoveField(
            model_name='adherenthistory',
            name='new_data',
        ),
    ]
