# Generated by Django 4.2 on 2023-05-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_old_data_adherenthistory_changes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structurehistory',
            old_name='old_data',
            new_name='changes',
        ),
        migrations.RemoveField(
            model_name='structurehistory',
            name='new_data',
        ),
    ]
