# Generated by Django 4.2 on 2023-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_old_data_structurehistory_changes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='commissions',
            field=models.CharField(blank=True, choices=[('Enseignement, Sciences et Technologies', 'Enseignement, Sciences et Technologies'), ('Développement et emploi', 'Développement et emploi'), ('Santé et social', 'Santé et social'), ('Culture, tourisme et environnement', 'Culture, tourisme et environnement'), ('Autre', 'Autre')], max_length=50, null=True),
        ),
    ]
