# Generated by Django 4.2 on 2023-04-23 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_delete_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='date_delivrance_ci',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='date_reglement_cotisation',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='date_validite_cs',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='derniere_cotisation_payee',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='document_identite',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='rue',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='ville',
        ),
        migrations.AddField(
            model_name='adherent',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='adherent',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
