# Generated by Django 4.2 on 2023-04-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_adherent_date_adhesion_alter_adherent_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='picture',
            field=models.ImageField(default='media/default.png', upload_to='images/'),
        ),
    ]
