# Generated by Django 4.2 on 2023-04-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_adherent_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
