# Generated by Django 4.2 on 2023-05-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_date_naissance_adherent_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adherent',
            old_name='email',
            new_name='adresse_email',
        ),
        migrations.RenameField(
            model_name='adherent',
            old_name='date_adhesion',
            new_name='date_adhésion',
        ),
        migrations.RenameField(
            model_name='adherent',
            old_name='nationalite',
            new_name='nationalité',
        ),
        migrations.RenameField(
            model_name='adherent',
            old_name='numero_document_identite',
            new_name='numero_document_identité',
        ),
        migrations.RenameField(
            model_name='adherent',
            old_name='telephone',
            new_name='numéro_de_téléphone',
        ),
        migrations.RenameField(
            model_name='adherent',
            old_name='image',
            new_name='photo_de_profile',
        ),
        migrations.RenameField(
            model_name='adherent',
            old_name='prenom',
            new_name='prénom',
        ),
        migrations.RenameField(
            model_name='adherent',
            old_name='type_adherent',
            new_name='type_adhérent',
        ),
        migrations.RenameField(
            model_name='adherent',
            old_name='type_document_identite',
            new_name='type_document_identité',
        ),
    ]
