# Generated by Django 4.2 on 2023-04-25 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0022_remove_adherent_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adherenthistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='adherenthistory',
            name='data',
        ),
        migrations.AddField(
            model_name='adherenthistory',
            name='new_data',
            field=models.TextField(blank=True, default='nothing', null=True),
        ),
        migrations.AddField(
            model_name='adherenthistory',
            name='old_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adherenthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adherenthistory',
            name='action',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='adherenthistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
