# Generated by Django 4.2 on 2023-05-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_email_structure_adresse_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banquetransactions',
            old_name='adherent',
            new_name='adhérent',
        ),
        migrations.RenameField(
            model_name='banquetransactions',
            old_name='cheque_numero',
            new_name='cheque_numéro',
        ),
        migrations.RenameField(
            model_name='banquetransactions',
            old_name='justificatif_banque',
            new_name='justificatif_bancaire',
        ),
        migrations.RenameField(
            model_name='banquetransactions',
            old_name='libelle',
            new_name='libellé',
        ),
        migrations.RenameField(
            model_name='banquetransactions',
            old_name='transaction_raison',
            new_name='raison_de_transaction',
        ),
        migrations.RenameField(
            model_name='banquetransactions',
            old_name='transaction_type',
            new_name='type_de_transaction',
        ),
        migrations.RenameField(
            model_name='banquetransactions',
            old_name='evenement',
            new_name='évènement',
        ),
        migrations.RenameField(
            model_name='caissetransactions',
            old_name='adherent',
            new_name='adhérent',
        ),
        migrations.RenameField(
            model_name='caissetransactions',
            old_name='libelle',
            new_name='libellé',
        ),
        migrations.RenameField(
            model_name='caissetransactions',
            old_name='transaction_raison',
            new_name='raison_de_transaction',
        ),
        migrations.RenameField(
            model_name='caissetransactions',
            old_name='recu_numero',
            new_name='recu_numéro',
        ),
        migrations.RenameField(
            model_name='caissetransactions',
            old_name='transaction_type',
            new_name='type_de_transaction',
        ),
        migrations.RenameField(
            model_name='caissetransactions',
            old_name='evenement',
            new_name='évènement',
        ),
        migrations.RenameField(
            model_name='cotisation',
            old_name='adherent',
            new_name='adhérent',
        ),
        migrations.RenameField(
            model_name='cotisation',
            old_name='libelle',
            new_name='libellé',
        ),
        migrations.RenameField(
            model_name='cotisation',
            old_name='number',
            new_name='numéro_chèque_ou_recu',
        ),
        migrations.RenameField(
            model_name='cotisation',
            old_name='cotisation_type',
            new_name='type_de_cotisation',
        ),
    ]
