# Generated by Django 4.2 on 2023-05-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_rename_adherent_banquetransactions_adhérent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banquetransactions',
            old_name='cheque_numéro',
            new_name='numéro_du_chèque',
        ),
    ]
