# Generated by Django 4.2 on 2023-05-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_cheque_numéro_banquetransactions_numéro_du_chèque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='justificatif',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
