# Generated by Django 4.2 on 2023-05-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_cotisation_justificatif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetransactions',
            name='raison_de_transaction',
            field=models.CharField(choices=[('Don', 'Don'), ('Cotisation', 'Cotisation'), ('Frais', 'Frais'), ('Profits', 'profits')], default='raison inconnue', max_length=20),
        ),
        migrations.AlterField(
            model_name='caissetransactions',
            name='raison_de_transaction',
            field=models.CharField(choices=[('Don', 'Don'), ('Cotisation', 'Cotisation'), ('Frais', 'Frais'), ('Profits', 'profits')], default='raison inconnue', max_length=20),
        ),
    ]
