# Generated by Django 4.2 on 2023-05-31 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_banquetransactions_raison_de_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquetransactions',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.structure'),
        ),
        migrations.AlterField(
            model_name='caissetransactions',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.structure'),
        ),
    ]
