# Generated by Django 4.2 on 2023-05-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_banquetransactions_type_de_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='photo_de_profile',
            field=models.ImageField(blank=True, default='img/default_profile_pic.jpg', null=True, upload_to='img/'),
        ),
    ]
